spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # 认证中心
      - id: tz-auth
        uri: lb://tz-auth
        predicates:
        - Path=/auth/**
        filters:
          # 验证码处理
        - ValidateCodeGatewayFilter
          # 前端密码解密
        - PasswordDecoderFilter
      #UPMS 模块
      - id: tz-upms
        uri: lb://tz-upms
        predicates:
        - Path=/admin/**
        filters:
          # 限流配置
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
          # 降级配置
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback'
      # 代码生成模块
      - id: tz-codegen
        uri: lb://tz-codegen
        predicates:
        - Path=/gen/**
      # 数据库查询模块
      - id: tz-dbquery
        uri: lb://tz-dbquery
        predicates:
        - Path=/dbquery/**


security:
  encode:
    # 前端密码密钥，必须16位
    key: 'thanks,tz4clouds'

# 不校验验证码终端
ignore:
  clients:
    - test
